#!/bin/bash
#applet_name=jive3.MainPanel
applet_name=HDBViewer.MainPanel

if [ ! $TANGO_HOST ] && [ -f /etc/tangorc ]; then
   . /etc/tangorc
fi

#
# Define the CLASSPATH
#

BASEDIR=$(dirname "$0")
echo "$BASEDIR"
echo "************"
JAVALIB=/home/user/tango-9.3.3-rc2/share/java;
JAVABIN=/home/user/tango-9.3.3-rc2/share/java;

ATK=$JAVALIB/ATKCore.jar:$JAVALIB/ATKWidget.jar:$JAVABIN/ATKPanel.jar
LOGVIEWER=$JAVALIB/LogViewer.jar
ASTOR=$JAVALIB/Astor.jar:$JAVALIB/tools_panel.jar
LOG4J=$JAVALIB/log4j.jar
LOGBACK=${TANGO_LOGBACK:-/home/user/tango-9.3.3-rc2/share/tango/logback.xml}

TANGO=$BASEDIR/JTango.jar
TANGOATK=$BASEDIR/ATKCore.jar:$BASEDIR/ATKWidget.jar
HDBVIEWER=$BASEDIR/jhdbviewer.jar
HDBPP=$BASEDIR/HDBPP.jar
JYTHON=$BASEDIR/jython.jar
JCALENDAR=$BASEDIR/jcalendar.jar

HDB_TYPE=mysql
HDB_MYSQL_HOST=archiver-maria-db
HDB_MYSQL_PORT=3307
HDB_USER=tango
HDB_PASSWORD=tango
HDB_NAME=hdbpp
CLASSPATH=$TANGO:$TANGOATK:$HDBVIEWER:$HDBPP:$JYTHON:$JCALENDAR

export HDB_TYPE
export HDB_MYSQL_HOST
export HDB_USER
export HDB_PASSWORD
export HDB_NAME
export HDB_MYSQL_PORT
export CLASSPATH

echo "************"
echo $CLASSPATH
echo "************"
echo $HDBVIEWER
echo "************"

#java -classpath $CLASSPATH -Djava.util.logging.config.file=log.properties -DTANGO_HOST=$TANGO_HOST HDBViewer.MainPanel $@
java -Djava.util.logging.config.file=log.properties -DTANGO_HOST=$TANGO_HOST HDBViewer.MainPanel $@
#/usr/bin/java \
#    -mx128m \
#    -DTANGO_HOST=$TANGO_HOST \
#    -Djava.util.logging.config.file=log.properties \
#    $applet_name $@

#/usr/bin/java \
#    -mx128m \
#    -DTANGO_HOST=$TANGO_HOST \
#    -Dlogback.configurationFile="$LOGBACK" \
#    $applet_name $@